name: Deploy Docs
on: [push, pull_request]
jobs:
  deploy-preview:
    if: github.branch != "main"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      # get a branch preview domain
      - name: Docusaurus BuildDeploy Action
        uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cf-githubactions-docs
      - name: Deploy
        run: aws s3 sync ./build s3://cf-release-docs-origin
